# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fName',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lName',
            new_name='last_Name',
        ),
    ]
