# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
